import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFile } from "fs/promises";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// pdf.js の worker を文字列として main.js にインライン埋め込みする。
// 配布を main.js + manifest.json の2ファイルだけで完結させ、別途
// pdf.worker.min.js をプラグインフォルダに配置する必要をなくす。
// （Obsidian/BRAT は Release から main.js/manifest.json しか取らないため）
const inlinePdfWorkerPlugin = {
	name: "inline-pdf-worker",
	setup(build) {
		build.onLoad({ filter: /pdfjs-dist.*pdf\.worker\.min\.js$/ }, async (args) => {
			const contents = await readFile(args.path, "utf8");
			return {
				contents: `export default ${JSON.stringify(contents)};`,
				loader: "js",
			};
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	plugins: [inlinePdfWorkerPlugin],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
